language: c

jobs:
  include:
    - os: linux
        - ARCH=amd64
      sudo: required
      addons:
        apt:
          packages:
            - build-essential
            - gperf
            - xorg-dev
            - libglu1-mesa-dev
            - libasound2-dev
            - mesa-common-dev
            - libx11-dev
            - libxrandr-dev
            - libxi-dev
            - xorg-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libgl1-mesa-glx
            - libglapi-mesa
            - libgles2-mesa-dev
            - mingw-w64
before_script:
  - cd test
  - gem install git && gem install rubyzip
  - cd ..
script:
  - rake -m
addons:
  apt:
    packages:
      - gperf
      - xorg-dev
      - libglu1-mesa-dev
