language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf cmake ruby
before_script:
  - gem update --system 2.7.5
script:
  - rake
