language: c

jobs:
  include:
    - os: linux
      env:
        - ARCH=amd64
        - INSTALL_GLFW=YES
        - USE_EXTERNAL_GLFW=OFF
      sudo: required
      addons:
        apt:
          packages:
            - build-essential
            - gperf
            - xorg-dev
            - libglu1-mesa-dev
            - libasound2-dev
            - mesa-common-dev
            - libx11-dev
            - libxrandr-dev
            - libxi-dev
            - xorg-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libgl1-mesa-glx
            - libglapi-mesa
            - libgles2-mesa-dev
    - os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install bison
        - export PATH="/usr/local/opt/bison/bin:$PATH"
      osx_image: xcode7.1
      compiler: clang
      sudo: required
      env:
        - ARCH=amd64
        - MRUBY_CONFIG=travis_config.rb
    - os: linux
      env:
        - WINDOW_CROSS_COMPILER=mingw
        - ARCH=amd64
      sudo: required
      addons:
        apt:
          packages:
            - build-essential
            - gperf
            - xorg-dev
            - libglu1-mesa-dev
            - libasound2-dev
            - mesa-common-dev
            - libx11-dev
            - libxrandr-dev
            - libxi-dev
            - xorg-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libgl1-mesa-glx
            - libglapi-mesa
            - libgles2-mesa-dev
            - mingw-w64
before_script:
  - cd test
  - gem install git && gem install rubyzip
  - cd ..
script:
  - rake -m
addons:
  apt:
    packages:
      - gperf
      - xorg-dev
      - libglu1-mesa-dev
